name: Renovate

on:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: renovatebot/renovate@latest
        with:
          token: ${{ secrets.test }}
